name: robbinlaw
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  google_fonts:
  font_awesome_flutter:
  sqflite:
  path:
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/

  fonts:
    - family: Chilanka-Regular
      fonts:
        - asset: lib/assets/fonts/Chilanka-Regular.ttf